/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_myapplication_HelloJni */

#ifndef _Included_com_example_myapplication_HelloJni
#define _Included_com_example_myapplication_HelloJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_myapplication_HelloJni
 * Method:    helloJniJava
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_myapplication_HelloJni_helloJniJava
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
